test_format = 1.0

[default]


    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.mail_address = "invoiceninja@domain.tld"
    args.mail_name = "invoiceninja"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.0e2b033a71b7401e7b1e0180780cc0096f1834a5.name = "Upgrade from 5.5.122"


